"use client"
import React from 'react'
import {  Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";



const PDFDocument = ({ grievance = {}, proofs = [], translations = {} }) => {
  //  console.log(proofs)
    const styles = StyleSheet.create({
        page: { padding: 20, fontSize: 12, fontFamily: "Helvetica" },
        section: { marginBottom: 10 },
        title: { fontSize: 16, fontWeight: "bold", marginBottom: 8 },
        text: { marginBottom: 4 },
        image: { width: 200, marginVertical: 10 },
        footer: { marginTop: 20, textAlign: "center", fontSize: 10 },
      });
    
  return (
    <div>
        <Document>
    <Page style={styles.page}>
      <Text style={styles.text}>{new Date(grievance.createdAt).toLocaleDateString()}</Text>
      <Text style={styles.text}>
        <strong>{translations.toLabel}</strong> 
      </Text>
      <Text style={styles.text}>
        <strong>{translations.officerTitle}</strong>
      </Text>
      <Text style={styles.text}>
        <strong>{translations.subjectLabel}</strong> {grievance.grievanceSubject}
      </Text>
      <Text style={styles.section}>{translations.salutation}</Text>
      {/* <Text style={styles.section}>{grievance.grievanceDetails}</Text> */}
      <Text style={styles.section}>{translations.faithfullyYours}</Text>
      <Text>{grievance.user.userName}</Text>
      <Text>{grievance.user.userPhone}</Text>
      <Text style={styles.title}>{translations.attachmentsLabel}:</Text>
      {proofs?.map((proof, index) => (
        <View key={index} style={styles.section}>
          <Text>
            {index + 1}. {proof.details || "No details given"}
          </Text>
          {["jpg", "jpeg", "png", "gif", "bmp", "webp", "svg"].includes(proof.file.split('.').pop().toLowerCase()) ? (
            // eslint-disable-next-line jsx-a11y/alt-text
            <Image  style={styles.image} src={`${process.env.NEXT_PUBLIC_IMAGE_URL}${proof.file}`} />
          ) : (
            <Text>This file is not an image type. Please print it separately.</Text>
          )}
        </View>
      ))}
      <Text style={styles.footer}>Generated by Grievance Portal</Text>
    </Page>
  </Document>
    </div>
  )
}

export default PDFDocument;
